GREETING = "Welcome to the King Simulator!"
PLOT_1 = "After the death of the last king, the throne passed to you."
PLOT_2 = "You are still young, you do not have the influence and authority of the previous ruler."
GM_DSCRPTN_1 = "Therefore, your power relies on the support of the CHURCH, the ARMY and the PEOPLE."
GM_DSCRPTN_2 = "There is also a TREASURY at your disposal from which you can finance various initiatives."
GM_DSCRPTN_3 = ("Do not forget about the other rulers of neighboring kingdoms. "
                "Your actions may affect their attitude towards you.")
START = "Let's start with your name: "
PRIORITY = "Before your reign begins, enter the name of the new king."
USER = "Please enter a name: "